export enum PARTNER_ENVIRONMENT {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
}

export enum PARTNER_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum SCOPE {
  CONSENT_GENERATE = 'CONSENT_GENERATE',
  CONSENT_VERIFY = 'CONSENT_VERIFY',
  CONSENT_REVOKE = 'CONSENT_REVOKE',
  CONSENT_BEACON = 'CONSENT_BEACON',
  AUDIT_LOG = 'AUDIT_LOG',
}

export enum RATE_LIMIT_TIER {
  FREE = 'FREE',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}
