export enum ApiErrorCode {
  SERVER = 'SERVER',
  USER = 'USER',
  CONTENT = 'CONTENT',
  VALIDATION = 'VALIDATION',
  FILE_STORAGE = 'FILE_STORAGE',
  SYSTEM = 'SYSTEM',
  PARTNER = 'PARTNER',
  RATE_LIMIT = 'RATE_LIMIT',
  CONSENT = 'CONSENT',
  AUTH = 'AUTH',
}
