export enum AuditStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  REVOKE = 'REVOKE',
  VERIFY = 'VERIFY',
  CONSENT_GENERATED = 'CONSENT_GENERATED',
  CONSENT_VERIFIED = 'CONSENT_VERIFIED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  CONSENT_BEACON = 'CONSENT_BEACON',
  CONSENT_RETRIEVED = 'CONSENT_RETRIEVED',
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
  CONSENT_AUTO_RENEWED = 'CONSENT_AUTO_RENEWED',
}
